/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */

plugins {
    java
}

tasks.named<Jar>("jar") {
    doFirst {
        println("Setting Manifest")
    }

    manifest {
        attributes["Main-Class"] = "emg.gradle.themepark.RideStatusService"
    }

    from(configurations.runtimeClasspath.get().map {
        if (it.isDirectory) it else zipTree(it)
    })
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.named("clean") {
    delete("bin")
}

repositories {
    mavenCentral()
}


val lombokVersion by extra("1.18.24")
val slf4jVersion by extra("2.0.0")
val junitVersion by extra("5.9.0")

dependencies {
    compileOnly("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")

    implementation("org.slf4j:slf4j-api:$slf4jVersion")
    runtimeOnly("org.slf4j:slf4j-simple:$slf4jVersion")

    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-params:$junitVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
}

tasks.withType(Test::class.java) {
    useJUnitPlatform()
}