/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multi.project.example

import emg.gradle.multiproject.MessageService

class App {
    fun greetings(): String {
        val messageService = MessageService()
        return messageService.generateMessage()
    }
}

fun main() {
    println(App().greetings())
}
